### ISSUE TITLE
解析发生错误

### ISSUE THREAD

**Issue by YongHuiBai** [liyinchigithub/Charles2Postman#4]
[2020-07-09T12:02:53.960] [INFO] default - 返回文件数组列表:.DS_Store,Untitled.chlsj
[2020-07-09T12:02:53.967] [INFO] default - [ 'File/.DS_Store', 'File/Untitled.chlsj' ]
undefined:1

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/bai/Desktop/Charles2Postman/index.js:2:10903
    at Array.forEach (<anonymous>)
    at Object.getFilesName (/Users/bai/Desktop/Charles2Postman/index.js:2:10422)
    at Object.<anonymous> (/Users/bai/Desktop/Charles2Postman/index.js:2:18214)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by liyinchigithub** [comment]
已修复
请下载V1.3 或 pull下

https://github.com/liyinchigithub/Charles2Postman/releases/tag/V1.3

**Comment by liyinchigithub** [comment]
![image](https://user-images.githubusercontent.com/19643260/87032017-884c6b00-c216-11ea-962f-38e8b8f6cbd1.png)
