### ISSUE TITLE
抛了个异常，这个怎么解决？

### ISSUE THREAD

**Issue by testerskp** [liyinchigithub/Charles2Postman#9]
开始转换
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'log4js'
Require stack:
- /Users/mazhigang3/Downloads/Charles2Postman-master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mazhigang3/Downloads/Charles2Postman-master/index.js:1:6785)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/mazhigang3/Downloads/Charles2Postman-master/index.js' ]
}

**Comment by testerskp** [comment]
没有安装依赖，问题已经解决
